# CI: runs on every push. Lint, check, test, build (dev), e2e.
when:
    - event: pull_request
    - event: push
      branch: main
    - event: tag
    - event: manual

steps:
    build:
        image: node:22-bookworm-slim
        commands:
            - corepack enable
            - corepack prepare pnpm@latest --activate
            - pnpm install --frozen-lockfile
            - pnpm run lint
            - pnpm run check
            - pnpm run test:run
            - pnpm run build
            - pnpm exec playwright install chromium --with-deps
            - pnpm run test:e2e
